"""Create the stable outer shell of a new AI structure work directory."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re


def normalize_identifier(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9_]+", "_", value.lower().replace("-", "_"))
    normalized = normalized.strip("_")
    if not normalized or normalized[0].isdigit():
        normalized = f"work_{normalized}"
    return normalized


def derived_dimension_id(namespace: str) -> int:
    digest = hashlib.sha256(namespace.encode("utf-8")).digest()
    return 600_000_000 + int.from_bytes(digest[:4], "big") % 300_000_000


def create_work(
    work_dir: Path,
    *,
    project_name: str,
    namespace: str,
    package: str,
    size: tuple[int, int, int],
    origin: tuple[int, int, int],
    dimension_id: int | None,
    dimension_biome: str | None,
    biome_inherits: str = "plains",
) -> None:
    work_dir = work_dir.resolve()
    if work_dir.exists() and any(work_dir.iterdir()):
        raise ValueError(f"refusing to overwrite non-empty directory: {work_dir}")
    namespace = normalize_identifier(namespace)
    package = normalize_identifier(package)
    dimension_id = dimension_id or derived_dimension_id(namespace)
    dimension_biome = dimension_biome or f"dm{dimension_id}_plains"
    source_dir = work_dir / "src" / package
    source_dir.mkdir(parents=True, exist_ok=True)

    project = {
        "schema_version": 1,
        "project_name": project_name,
        "namespace": namespace,
        "structure_name": "landmark",
        "builder": f"{package}:build_structure",
        "structure_size": list(size),
        "world_origin": list(origin),
        "dimension_id": dimension_id,
        "dimension_mod_id": namespace,
        "dimension_biome": dimension_biome,
        "biome_inherits": biome_inherits,
        "repeat_period": 4096,
        "worldgen_piece_size": [16, 256, 16],
        "modsdk_piece_size": [32, 64, 32],
        "modsdk_batch_size": 4,
        "modsdk_batch_delay": 0.25,
        "modsdk_passes": 3,
        "modsdk_pass_delay": 2.0,
    }
    (work_dir / "project.json").write_text(
        json.dumps(project, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (work_dir / ".gitignore").write_text("out/\n", encoding="utf-8")
    (work_dir / "main.py").write_text(_main_template(), encoding="utf-8")
    (source_dir / "__init__.py").write_text(
        '"""AI-authored structure generator."""\n\n'
        "from .build import build_structure\n\n"
        '__all__ = ["build_structure"]\n',
        encoding="utf-8",
    )
    (source_dir / "build.py").write_text(_builder_template(size), encoding="utf-8")
    (work_dir / "BRIEF.md").write_text(_brief_template(project_name), encoding="utf-8")


def _main_template() -> str:
    return '''"""One-command entry point; support files are generated by shared tooling."""

from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
REPOSITORY = next(
    parent for parent in HERE.parents if (parent / "pyproject.toml").is_file()
)
sys.path.insert(0, str(REPOSITORY))
sys.path.insert(0, str(REPOSITORY / "src"))

from scripts.structure_workflow.runner import run_work_entry  # noqa: E402


if __name__ == "__main__":
    raise SystemExit(run_work_entry(HERE))
'''


def _builder_template(size: tuple[int, int, int]) -> str:
    dense_bytes = size[0] * size[1] * size[2] * 4
    if dense_bytes >= 256 * 1024 * 1024:
        canvas_import = "Block, StructurePlan"
        canvas_type = "StructurePlan"
    else:
        canvas_import = "Block, Structure"
        canvas_type = "Structure"
    return f'''"""Replace this starter with the architecture described in BRIEF.md."""

from mcstructure import {canvas_import}


SIZE = {size!r}
AIR = Block("minecraft:air")
FOUNDATION = Block("minecraft:stonebrick")


def build_structure() -> {canvas_type}:
    """Return one logical canvas; shared tooling handles every export format."""
    structure = {canvas_type}(SIZE, AIR)
    structure.set_blocks((0, 0, 0), (SIZE[0] - 1, 2, SIZE[2] - 1), FOUNDATION)
    return structure
'''


def _brief_template(project_name: str) -> str:
    return f"""# {project_name} — 建筑需求

把玩家需求写在这里，然后让 AI 只修改 `main.py` 与 `src/`。

## 核心概念

- 建筑主题：
- 叙事/用途：
- 第一眼必须看到的轮廓：
- Boss 或核心区域差异：

## 空间与路线

- 入口方向：负 Z
- 玩家主路线：
- 必须可进入的房间：
- 地标、庭院、地下或垂直层级：

## 风格与材料

- 建筑风格：
- 主材 / 次材 / 强调材：
- 禁止使用：

## 验收条件

- [ ] 从推荐传送点能看到并找到入口
- [ ] 主路线连续，无封死门洞或断梯
- [ ] 外轮廓、内部空间、照明和地标均已实现
- [ ] `python scripts/structure_work.py build <work目录>` 一次通过
"""
