"""One-command entry point; support files are generated by shared tooling."""

from pathlib import Path
import sys


HERE = Path(__file__).resolve().parent
REPOSITORY = next(
    parent for parent in HERE.parents if (parent / "pyproject.toml").is_file()
)
sys.path.insert(0, str(REPOSITORY))
sys.path.insert(0, str(REPOSITORY / "src"))

from scripts.structure_workflow.runner import run_work_entry  # noqa: E402


if __name__ == "__main__":
    raise SystemExit(run_work_entry(HERE))
